server:
  port: 9010

spring:
  profiles:
    active: common   # 使用公共模块的yml合并到当前的yml
  application:
    name: producer   # 设置服务名称  会在Eureka中显示

demo:
  rocketmq:
    name-server: localhost:9876

    producer:
      group: demo-order
      send-message-timeout: 300000

    consumer:
      group: demo-order-paid