server:
  port: 1001
spring:
  # 配置数据库 参数
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.18.50.226:3306/demo?characterEncoding=utf8
    username: admin
    password: admin

  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: debug
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M:%L - %msg%n'